# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveBrewDog' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactiveBrewDog

        pod 'ReactiveSwift'
	pod 'ReactiveCocoa'
	pod 'SnapKit'


  target 'ReactiveBrewDogTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'ReactiveBrewDogUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
